In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import tensorflow as tf

In [ ]:
from google.colab import files
x = files.upload()

Saving Cleaned-Stroke-Data2.csv to Cleaned-Stroke-Data2.csv


# **TEST**

In [ ]:
data = pd.read_csv('Cleaned-Stroke-Data2.csv' , delimiter = ',')
data.head()

gender   age  hypertension  ...   bmi  smoking_status  stroke
0       0  67.0             0  ...  36.6               0       1
1       0  80.0             0  ...  32.5               1       1
2       1  49.0             0  ...  34.4               2       1
3       1  79.0             1  ...  24.0               1       1
4       0  81.0             0  ...  29.0               0       1

[5 rows x 11 columns]

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(data, data['stroke'])

In [ ]:
#x_train, x_test, y_train, y_test = train_test_split(data, data['stroke'], test_size=0.2, random_state=42)

In [ ]:
len(x_train)

3681

In [ ]:
len(y_train)

3681

In [ ]:
x_train = x_train.drop(columns="stroke")
x_test = x_test.drop(columns="stroke")


In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
lr = LogisticRegression(solver='lbfgs', max_iter=1000)
lr.fit(x_train, y_train)

LogisticRegression(max_iter=1000)

In [ ]:
y_predlr = lr.predict(x_test)

In [ ]:
lr.score(x_test, y_test)

0.9609120521172638

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
accLR = accuracy_score(y_test, y_predlr)
accLR

0.9609120521172638

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
from sklearn.utils.multiclass import unique_labels
unique_labels(y_test)

array([0, 1])

In [ ]:
from sklearn.metrics import confusion_matrix
def plot_confusion_matrix(y_true, y_pred):
    labels = unique_labels(y_true)
    columns = [f'Predicted {label}' for label in labels]
    index = [f'Actual {label}' for label in labels]
    table = pd.DataFrame(confusion_matrix(y_true, y_pred), 
                         columns=columns, index=index)
    return table

plot_confusion_matrix(y_test, y_predlr)

Predicted 0  Predicted 1
Actual 0         1180            1
Actual 1           47            0

In [ ]:
lr.classes_

array([0, 1])

In [ ]:
lr.coef_

array([[ 0.06828887,  0.07033424,  0.63677602,  0.2845249 ,  0.00613734,
        -0.1061021 ,  0.1806784 ,  0.00572474,  0.00384209, -0.0856109 ]])

In [ ]:
x_train.head()

gender   age  hypertension  ...  avg_glucose_level   bmi  smoking_status
4533       1  24.0             0  ...             114.54  30.1               2
3564       0   8.0             0  ...             121.99  19.6               3
910        1  55.0             0  ...             112.47  32.8               2
426        0  68.0             0  ...              92.21  27.3               3
3823       1  27.0             0  ...             139.20  36.2               1

[5 rows x 10 columns]

In [ ]:
lr.intercept_

array([-7.76470129])

In [ ]:
columns = x_train.columns

In [ ]:
coefficients = pd.Series(lr.coef_[0], columns)
coefficients

gender               0.068289
age                  0.070334
hypertension         0.636776
heart_disease        0.284525
ever_married         0.006137
work_type           -0.106102
Residence_type       0.180678
avg_glucose_level    0.005725
bmi                  0.003842
smoking_status      -0.085611
dtype: float64

In [ ]:
plot_confusion_matrix(y_test, y_predlr)

Predicted 0  Predicted 1
Actual 0         1180            1
Actual 1           47            0

In [ ]:
True_positive = 1
True_negative = 1185
False_positive = 0
False_negative = 42

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_predlr))

              precision    recall  f1-score   support

           0       0.96      1.00      0.98      1181
           1       0.00      0.00      0.00        47

    accuracy                           0.96      1228
   macro avg       0.48      0.50      0.49      1228
weighted avg       0.92      0.96      0.94      1228



In [ ]:
recall = True_positive/(True_positive + False_negative)
recall

0.023255813953488372

In [ ]:
precision = True_positive/(True_positive + False_positive)
precision

1.0

In [ ]:
f1_score = (precision * recall / (precision + recall)) * 2
f1_score

0.04545454545454545



recall - Identify only cases that matter the most

number of relevant result/ total number of all relevant results

True positive/true positive + false negative

precision - Identify all positive cases

number of relevant result (information) / all available results. 

true positives / true positive + false positive